FROM alpine:latest AS getfiles
# install git
RUN apk add git
RUN mkdir /src
WORKDIR /src
RUN git clone https://www.github.com/kevinmcaleer/ClusteredPi

FROM blafy/jekyll as jekyll
COPY --from=getfiles /src/ClusteredPi/web /src
WORKDIR /src
RUN mkdir /src/_site
RUN echo $UID
RUN jekyll build 

FROM nginx
COPY --from=getfiles /src/ClusteredPi/stacks/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=jekyll /src/_site /www/data


# RUN cp /src /www/data