FROM alpine:3.17.5 AS getfiles
# install git
RUN echo 'grabing hostname'
RUN echo 'hostname='$HOSTNAME >> _config.yml
RUN cat _config.yml
RUN echo "installing git"
RUN apk --no-cache add git
RUN mkdir /src
WORKDIR /src
RUN echo "cloning kevsrobots"
RUN git clone --depth=1 https://www.github.com/kevinmcaleer/kevsrobots.com.git --recurse-submodules --remote-submodules
RUN ls -la

FROM alpine:latest as secondstage
RUN apk add --virtual build-dependencies build-base
RUN apk add ruby-dev
RUN echo "making /src"

# COPY --from=getfiles /src/kevsrobots.com/web /src
COPY --from=getfiles /src/kevsrobots.com/web /src
WORKDIR /src
RUN mkdir -p /src/_site

RUN echo "Cloned kevsrobots.com"

ENV BUILD_PACKAGES bash curl curl-dev ruby-dev build-base
ENV RUBY_PACKAGES \
  ruby ruby-io-console ruby-irb \
  ruby-json ruby-etc ruby-bigdecimal ruby-rdoc \
  libffi-dev zlib-dev
ENV TERM=linux
ENV PS1 "\n\n>> ruby \W \$ "

RUN apk --no-cache add $BUILD_PACKAGES $RUBY_PACKAGES

# FROM ruby as jekyll
# RUN apt-get update \ 
#    && apt-get install -y \
#    python3-pygments \
#    && apt-get clean \
#    && rm -rf /var/lib/apt/lists/*

RUN gem install --platform ruby google-protobuf
RUN gem install \
  # github-pages \
  jekyll \
  jekyll-redirect-from \
  kramdown \
  rdiscount \
  rouge \
  byebug \ 
  jekyll-sass-converter:3.0.0 \
  sass-embedded:1.64.1

# Build the site
RUN jekyll build --trace

FROM nginx
COPY --from=getfiles /src/kevsrobots.com/stacks/kevsrobots/nginx.conf /etc/nginx/nginx.conf
# COPY --from=jekyll /src/_site /www/data
COPY --from=secondstage /src/_site /www/data

