services:

  kevsrobots:
    environment:
      JEKYLL_UID: 1000
      JEKYLL_GID: 1000
      JEKYLL_ENV: production
      DOCKER_BUILDKIT: 1  # Enable BuildKit for faster builds
    build:
      context: .
      dockerfile: dockerfile  # Now uses optimized Dockerfile
    image: 192.168.2.1:5000/kevsrobots:latest  ## goes to local registry
    ports:
      - "3333:3333"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:3333/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    