version: "3.7"
services:
  metaduck:
    image: metaduck:latest
    container_name: metaduck
    ports:
      - "80:3000"
    environment:
      - MB_PLUGINS_DIR=/home/plugins
    volumes:
      - /Users/Kev/Python/ducklake/duckdb_utils:/data
    deploy:
      resources:
        limits:
          memory: 2g
    restart: unless-stopped
