services:
  nginx_load_balancer:
    build: .
    image: 192.168.2.1:5000/nginx 
    ports: 
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "8000:8000"
    # image: myapp
    restart: always
    # volumes:
    #   - /home/pi/ClusteredPi/certbot/conf:/etc/certbot:ro
    #   - /home/pi/ClusteredPi/certbot/data:/var/www/certbot:ro
  # certbot:
  #   image: certbot/certbot:arm32v6-latest
  #   container_name: certbot
  #   volumes:
  #     - /home/pi/ClusteredPi/certbot/conf:/etc/certbot:rw
  #     - /home/pi/ClusteredPi/certbot/data:/var/www/certbot:rw
  #   command: certonly --webroot -w /var/www/certbot --force-renewal --email kevinmcaleer@gmail.com -d clustered-pi.com --agree-tos --staging