FROM alpine:latest AS getfiles
# install git
RUN apk add git
RUN mkdir -m 700 /src
WORKDIR /src
RUN git clone --depth=1 https://www.github.com/kevinmcaleer/ClusteredPi.git

FROM nginx
COPY --from=getfiles /src/ClusteredPi/stacks/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=getfiles /src /www/data

# RUN cp /src /www/data