version: '3.8'

services:
  page-counter-minimal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: page-counter-minimal
    ports:
      - "8005:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
