services:
  chatter:
    build:
      context: https://github.com/kevinmcaleer/chatter.git
    ports:
      - "8005:8005"
    volumes:
      - ./data:/app/data
    environment:
      - SECRET_KEY=${SECRET_KEY}
    env_file:
      - .env
