services:
  chatter:
    # build:
    #   context: https://github.com/kevinmcaleer/chatter.git
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    volumes:
      - ./data:/data
    environment:
      - SECRET_KEY=${SECRET_KEY}
    env_file:
      - .env
