FROM python:3.11-slim

# Install git so we can clone the repo
RUN apt-get update && apt-get install -y git

# Set working directory
WORKDIR /

# create data folder
RUN mkdir -p ./data

# Set working directory
WORKDIR /app

# Clone the repository (latest main branch)
RUN git clone https://github.com/kevinmcaleer/chatter.git .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port
EXPOSE 8005

# Set working directory
WORKDIR /

# Run the app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8005", "--reload"]
