FROM alpine:latest AS getfiles
# install git
RUN apk --no-cache add git
RUN mkdir /src
WORKDIR /src
RUN git clone https://www.github.com/kevinmcaleer/pythonai 
WORKDIR /src/pythonai

# Install Python
RUN apk --no-cache add python3
RUN apk --no-cache add python3-dev
RUN apk --no-cache add build-essential 
RUN apk --no-cache add libssl-dev
RUN apk --no-cache add libffi-dev 
RUN python3 -m ensurepip --upgrade
RUN pip3 install --upgrade pip

# Install Vosk
RUN pip3 install vosk

# Create virtual environment
RUN python3 -m venv venv
RUN source venv/bin/activate

# Install Python dependencies
RUN pip3 install -r requirements.txt

# Run the application
RUN python3 alf.py