FROM alpine:latest AS getfiles
# install git
RUN apk --no-cache add git
RUN mkdir /src

WORKDIR /src
# RUN apk add --no-cache curl
RUN git clone https://www.github.com/kevinmcaleer/pythonai 
WORKDIR /src/pythonai

# Download Vosk model

# Large Model
# RUN curl https://alphacephei.com/vosk/models/vosk-model-en-us-0.22.zip -o model.zip && unzip model.zip && rm model.zip

# Small Model
ADD https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip /src/pythonai/model.zip

RUN unzip model.zip
RUN rm model.zip
RUN mkdir /src/pythonai/model
RUN mv /src/pythonai/vosk-model-small-en-us-0.15/vosk-model-small-en-us-0.15 /src/pythonai/model

# DEBUG
RUN ls 
RUN pwd

# Install Python
RUN apk --no-cache add python3
RUN apk --no-cache add python3-dev

# Install other dependencies
RUN apk --no-cache add libffi-dev gcc libc-dev
RUN apk --no-cache add portaudio portaudio-dev

# Create virtual environment
RUN python3 -m venv venv
RUN source /src/pythonai/venv/bin/activate
ENV PATH="/src/pythonai/venv/bin:$PATH"


RUN python3 -m ensurepip --upgrade
RUN pip3 install --upgrade pip

# Install Python dependencies
RUN pip3 install -r requirements.txt

# Install Vosk
RUN pip3 install vosk

# DEBUG
RUN ls 
RUN pwd

# Run the application
CMD ["/src/pythonai/venv/bin/python3", "alf.py"]