# Use Ubuntu as the base image for the first stage
FROM ubuntu:latest AS getfiles

# Install necessary tools and clone the repository
RUN apt-get update && apt-get install -y git \
    && mkdir /src \
    && cd /src \
    && git clone --depth=1 https://www.github.com/kevinmcaleer/ClusteredPi.git --recurse-submodules --remote-submodules \
    && ls -la /src

# Start with an Ubuntu base image for the Ruby stage
FROM ubuntu:latest AS secondstage

# Install Ruby and build dependencies
RUN apt-get update && apt-get install -y ruby-full build-essential zlib1g-dev

# Configure gem installation location and PATH for Ruby Gems
RUN echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc \
    && echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc \
    && echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc \
    && /bin/bash -c "source ~/.bashrc"

# Copy the cloned repository from the first stage
COPY --from=getfiles /src/kevsrobots.com/web /src
WORKDIR /src

# Install necessary gems
RUN gem install jekyll:4.3.3 jekyll-redirect-from kramdown rdiscount rouge byebug \
    && gem install jekyll-sass-converter:3.0.0 sass-embedded:1.64.1 \
    && gem install nokogiri \
    && gem install google-protobuf -v 3.25.2 \
    && gem install ruby

# Build the site
RUN jekyll build --trace

# Use Nginx to serve the site, starting with the official image
FROM nginx
COPY --from=getfiles /src/ClusteredPi/stacks/clusteredpi/nginx.conf /etc/nginx/nginx.conf
COPY --from=secondstage /src/_site /www/data
