# Use a Python base image compatible with ARM64
# FROM arm64v8/python:3.11-bookworm
# FROM buildpack-deps:bookworm

FROM alpine:latest AS getfiles
# install python3
RUN apk --no-cache add python3 python3-pip

# Install Jupyter Notebook
RUN pip install notebook --no-cache-dir

# Set up the working directory
WORKDIR /notebooks

# Expose the port Jupyter Notebook will run on
EXPOSE 8888

# Start Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root"]
