# Use an ARM64 compatible base image, such as Ubuntu
FROM arm64v8/ubuntu:latest

# Install Python and pip
RUN apt-get update -y && apt-get install -y --no-install-recommends python3 python3-pip python3-dev

# Clean up APT when done
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install Jupyter Notebook
RUN pip3 install notebook

# Set up the working directory
WORKDIR /notebooks

# Expose the port Jupyter Notebook will run on
EXPOSE 8888

# Start Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root"]
