version: '3.8'

services:
  netbox:
    build:
      context: https://github.com/tribp/netbox.git
      dockerfile: netbox/Dockerfile
    container_name: netbox
    ports:
      - "8001:8080"
    environment:
      SUPERUSER_NAME: admin
      SUPERUSER_EMAIL: admin@example.com
      SUPERUSER_PASSWORD: admin
    volumes:
      - netbox-media:/opt/netbox/netbox/media
    depends_on:
      - netbox-db
      - redis
      - redis-cache
    restart: unless-stopped

  netbox-db:
    image: postgres:15-alpine
    container_name: netbox-db
    environment:
      POSTGRES_DB: netbox
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: netbox
    volumes:
      - netbox-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: netbox-redis
    restart: unless-stopped

  redis-cache:
    image: redis:alpine
    container_name: netbox-redis-cache
    restart: unless-stopped

volumes:
  netbox-db-data:
  netbox-media:
