# Make sure you set up port forwarding on your home router as follows:
#    <home-router-external-ip>:51820 --> <rpi-running-vpn>:51820
#    <home-router-external-ip>:51821 --> <rpi-running-vpn>:51821

version: '3.8'

services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=<home-router-external-ip>  # Replace with your home router's IP address
      - PASSWORD=<your_secure_password>  # Replace with your secure password
    ports:
      - "51820:51820/udp"  # Port for the VPN connection
      - "51821:51821/tcp"  # Port for the web UI
    volumes:
      - ./data:/etc/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
